version: "3"
services:
  rabbitmq:
    image: rabbitmq-custom
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - webnet

  couchbase:
    image: couchbase-custom
    ports:
      - 8081:8091
      - 8082:8092
      - 8083:8093
    networks:
      - webnet



  photo-service:
    image: photos-app
    ports:
      - 8080:8080
    depends_on:
      - couchbase
      - rabbitmq
    networks:
      - webnet

networks:
  webnet:
    external: true

