version: "3"
services:
  couchbase:
    image: couchbase-custom
    ports:
      - 8081:8091
      - 8082:8092
      - 8083:8093
    networks:
      - webnet
  web:
    # replace username/repo:tag with your name and image details
    image: photos-app
    ports:
      - 8080:8080
    depends_on:
      - couchbase
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

